#!/usr/bin/env sh

token="FIXME"
manual="./FIXME.md"
folder="./include"
origin="./include/xtal.c++"
target="./include/FIXME.cxx"
offset=3
source="*.c++"
sourced="all.c++"

function help {
	cat "${manual}"
	exit 0
}
function print_target {
	[ -s "${target}" ] && cat "${target}"
}
function clean_target {
	[ -s "${target}" ] || rm "${target}"
}
function clear_target {
	truncate -s 0 "${target}"
}

function origins_ {
	find -s "${folder}" -depth ${offset} -name "${source}"
}
function sources_ {
	grep -lR --include "${source}" "${token}" "${folder}" | sort
}
function _include {
	sed 's|\./|#|' | sed 's|/| "./|' | sed 's|$|"|'
}
function _any_ {
	grep -v "${sourced}"
}
function _all_ {
	grep "${sourced}"
}

sources_|_include > "${target}"
case "${1}" in
--help) help;;
++)     origins_|_any_|_include > "${target}";;
+)      origins_|_all_|_include > "${target}";;
.)      clear_target;;
esac
print_target
clean_target
