#!/usr/bin/env sh

grep -lR FIXME ./include | grep .c++ |\
	sed 's|\./|#|' | sed 's|/| "./|' | sed 's|$|"|' > ./include/xtal.cxx

[ -s ./include/xtal.cxx ] && cat ./include/xtal.cxx
[ -s ./include/xtal.cxx ] || rm ./include/xtal.cxx
