#pragma once
#include "./common/all.cc"
#include "./concord/all.cc"
#include "./conduct/all.cc"
#include "./conflux/all.cc"
#include "./prepare/all.cc"
#include "./message/all.cc"
#include "./process/all.cc"
#include "./processor/all.cc"
