#pragma once
#include "./compound/all.cc"
#include "./concord/all.cc"
#include "./conflux/all.cc"
#include "./content/all.cc"
#include "./context/all.cc"
#include "./control/all.cc"
#include "./process/all.cc"
#include "./processor/all.cc"
