name: Conan Create

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create:

    strategy:
      matrix:
        bt: [Debug, Release]
        os: [macos, ubuntu] #, windows]
    
    runs-on: ${{matrix.os}}-latest

    steps:
    - uses: actions/checkout@v3
    
    - run:  brew install conan
      if:   ${{ matrix.os == 'macos' }}

    - run:  pip3 install wheel setuptools; pip3 install conan --upgrade
      if:   ${{ matrix.os != 'macos' }}

    - run:  conan remote update conancenter --url="https://center2.conan.io"
    - run:  conan config install ${{github.workspace}}/.conan2

    - run:  conan create ${{github.workspace}} --build=missing -s build_type=${{matrix.bt}} --profile:all=${{matrix.os}}
      if:   ${{ matrix.bt != 'Release' }}

    - run:  conan create ${{github.workspace}} --build=missing -s build_type=${{matrix.bt}} --profile:all=${{matrix.os}} -o "test_package/*:benchmark=True"
      if:   ${{ matrix.bt == 'Release' }}
